name: T3

on:
  issue_comment:
    types: [created, edited]
  
jobs:

  build:
    if: (
          github.event.issue.pull_request &&
          contains(
            fromJson('["test", "build android", "build"]'),
            github.event.comment.body
          )
        )
    name: T3
    runs-on: macos-latest
  
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 5
          
    - name: Run Test T3
      run: |
        echo 'github.event.comment.body'=${{ github.event.comment.body }}
        echo 'steps.sha.outputs.result'= steps.sha.outputs.result
        echo 'github.event.pull_request.head.sha'=${{ github.event.pull_request.head.sha }}
        cat ./script/t1.sh
        echo '------'
        ./script/t1.sh
      env:
        TT_S: ${{ secrets.TT_S }}
