name: T3

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
  
jobs:

  build:
    name: T3
    runs-on: macos-latest
  
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
          
    - name: Run Test T3
      run: |
        echo 'github.head_ref'=${{ github.head_ref }}
        echo 'github.event.pull_request.head.sha'=${{ github.event.pull_request.head.sha }}
        cat ./script/t1.sh
        echo '***'
        echo '------'
        echo 'TT_S_s'
        echo '------'
        ./script/t1.sh ${{ secrets.TT_S }} 
      env:
        TT_S: ${{ secrets.TT_S }}  
